### ISSUE TITLE
On sorting and grouping imports as a goal

### ISSUE THREAD

**Issue by softprops** [jD91mZM2/rust-import#1]
These goals may be a better fit for rustfmt and in fact it may already support some of this.

It would be great for these two tools to compliment each other. What rustfmt does not do with imports is fill in the blanks. Which is the perfect goal for this tool.

**Comment by jD91mZM2** [comment]
Thanks for the input!

Rustfmt does support sorting at least, but I myself am not a huge fan of rustfmt (even though I probably should be).  
Preferrably, when/if https://github.com/dtolnay/syn/issues/294 gets fixed, I could avoid the dependency on rustfmt all together. And that's where sorting/grouping comes in.

Although, this is just my opinion.

**Comment by jD91mZM2** [comment]
@softprops?

**Comment by jD91mZM2** [comment]
I'd love to have an argument on whether or not this fits within the goals of rust-import, but for now I'll close this issue for inactivity.
